In [7]:
import numpy as np
import math 

In [8]:
list = [1, 2, 3, 4, 5]
array = np.array(list)
print(array)

[1 2 3 4 5]


In [10]:
matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_2d = np.array(matrix_data)
print(matrix_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [14]:
range_array = np.arange(0, 25, 5)
print(range_array)

[ 0  5 10 15 20]


In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print(array)

[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
data_array = np.array([12, 15, 18, 22, 25, 28, 31, 35, 40, 45])

print(data_array)
print(np.mean(data_array))

[12 15 18 22 25 28 31 35 40 45]
27.1


In [15]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])


multip= a * b
print(multip)

[ 10  40  90 160 250]


In [17]:
array = np.array([[10, 20, 30, 40], 
                         [50, 60, 70, 80], 
                         [90, 100, 110, 120]])
f= array[:2, :]  # Первые две строки, все столбцы
print(f)

[[10 20 30 40]
 [50 60 70 80]]
